Task 1: Unit Conversion

In [3]:
def convert_units(category, value):
  if category == "m to ft":
    return value * 3.28084
  elif category == "ft to m":
    return value / 3.28084
  elif category == "kg to lbs":
    return value * 2.20462
  elif category == "lbs to kg":
    return value / 2.20462
  elif category == "L to gal":
    return value * 0.264172
  elif category == "gal to L":
    return value / 0.264172
  else:
    return None

def main():
  print("Unit Converter")
  print("1. Length (m to ft, ft to m)")
  print("2. Weight (kg to lbs, lbs to kg)")
  print("3. Volume (L to gal, gal to L)")

  choices = {
      "1": ["m to ft", "ft to m"],
      "2": ["kg to lbs", "lbs to kg"],
      "3": ["L to gal", "gal to L"],
  }

  choice = input("Choose a category (1-3): ")
  if choice not in choices:
    print("Invalid choice. Exiting.")
    return

  print(f"Available conversions: {choices[choice][0]}, {choices[choice][1]}")
  conversion_type = input("Enter conversion type: ")

  if conversion_type not in choices[choice]:
    print("Invalid conversion type. Exiting.")
    return

  try:
    value = float(input("Enter the value to convert: "))
    result = convert_units(conversion_type, value)
    if result is not None:
      print(f"Converted value: {result:.2f}")
    else:
      print("Conversion not supported.")
  except ValueError:
    print("Invalid input. Please enter a numeric value.")

if __name__ == "__main__":
  main()

Unit Converter
1. Length (m to ft, ft to m)
2. Weight (kg to lbs, lbs to kg)
3. Volume (L to gal, gal to L)
Choose a category (1-3): 1
Available conversions: m to ft, ft to m
Enter conversion type: m to ft
Enter the value to convert: 12
Converted value: 39.37


Task 2: Mathematical Operations

In [4]:
def calculate_sum(numbers):
  return sum(numbers)

def calculate_average(numbers):
  return sum(numbers) / len(numbers) if numbers else None

def find_maximum(numbers):
  return max(numbers)

def find_minimum(numbers):
  return min(numbers)

def main():
  print("Mathematical Operations on a List of Numbers")
  print("1. Sum")
  print("2. Average")
  print("3. Maximum")
  print("4. Minimum")

  operations = {
      "1": calculate_sum,
      "2": calculate_average,
      "3": find_maximum,
      "4": find_minimum
  }

  choice = input("Choose an operation (1-4): ")
  if choice not in operations:
    print("Invalid choice. Exiting.")
    return

  try:
    numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
    if not numbers:
      raise ValueError("List cannot be empty.")

    result = operations[choice](numbers)
    print(f"Result: {result}")
  except ValueError:
    print("Invalid input. Please enter numeric values.")

if __name__ == "__main__":
  main()

Mathematical Operations on a List of Numbers
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 3
Enter numbers separated by spaces: 1 4 2 8 9 11 3 5
Result: 11.0


Task 3 : List Manipulations

In [5]:
def extract_every_other(lst):
  return lst[::2]

def get_sublist(lst, start, end):
  return lst[start:end+1]

def reverse_list(lst):
  return lst[::-1]

def remove_first_last(lst):
  return lst[1:-1]

def get_first_n(lst, n):
  return lst[:n]

def get_last_n(lst, n):
  return lst[-n:]

def reverse_skip(lst):
  return lst[-2::-2]

lst = [1, 2, 3, 4, 5, 6]
print("Every other element:", extract_every_other(lst))
print("Sublist (2,4):", get_sublist(lst, 2, 4))
print("Reversed list:", reverse_list(lst))
print("Without first and last:", remove_first_last(lst))
print("First 3 elements:", get_first_n(lst, 3))
print("Last 2 elements:", get_last_n(lst, 2))
print("Reverse skip:", reverse_skip(lst))

Every other element: [1, 3, 5]
Sublist (2,4): [3, 4, 5]
Reversed list: [6, 5, 4, 3, 2, 1]
Without first and last: [2, 3, 4, 5]
First 3 elements: [1, 2, 3]
Last 2 elements: [5, 6]
Reverse skip: [5, 3, 1]


Task 4: Nested List Operations

In [6]:
def flatten(lst):
  return [item for sublist in lst for item in (flatten(sublist) if isinstance(sublist, list) else [sublist])]

def access_nested_element(lst, indices):
  for index in indices:
    lst = lst[index]
  return lst

def sum_nested(lst):
  return sum(flatten(lst))

def remove_element(lst, elem):
  return [[x for x in sublist if x != elem] for sublist in lst]

def find_max(lst):
  return max(flatten(lst))

def count_occurrences(lst, elem):
  return flatten(lst).count(elem)

def deep_flatten(lst):
  return flatten(lst)

def average_nested(lst):
  flat = flatten(lst)
  return sum(flat) / len(flat)

nested_lst = [[1, 2], [3, [4, 5]], 6]
print("Flatten list:", flatten(nested_lst))
print("Accessing [1, 2]:", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print("Sum of elements:", sum_nested(nested_lst))
print("Remove 2:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("Max element:", find_max(nested_lst))
print("Count 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("Deep Flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print("Average:", average_nested([[1, 2], [3, 4], [5, 6]]))

Flatten list: [1, 2, 3, 4, 5, 6]
Accessing [1, 2]: 6
Sum of elements: 21
Remove 2: [[1], [3], [4, 5]]
Max element: 6
Count 2: 3
Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Average: 3.5


#NumPy Exercises
Task 1: Creating and Manipulating NumPy Arrays

In [7]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_zeros = np.zeros((2, 3))
arr_ones = np.ones((3, 2))
arr_random = np.random.rand(3, 3)

print("1D Array:", arr_1d)
print("2D Array:", arr_2d)
print("Zeros Array:", arr_zeros)
print("Ones Array:", arr_ones)
print("Random Array:", arr_random)

reshaped_arr = arr_1d.reshape(5, 1)
print("Reshaped 1D Array:", reshaped_arr)

print("Element at (0, 1):", arr_2d[0, 1])
print("First row:", arr_2d[0])
print("Last column:", arr_2d[:, -1])

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]
Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: [[1. 1.]
 [1. 1.]
 [1. 1.]]
Random Array: [[0.77210449 0.83759288 0.05367906]
 [0.36600928 0.22044285 0.7383022 ]
 [0.98368954 0.65655544 0.22843912]]
Reshaped 1D Array: [[1]
 [2]
 [3]
 [4]
 [5]]
Element at (0, 1): 2
First row: [1 2 3]
Last column: [3 6]


Task 2:  NumPy Array Operations

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

print("Exponential:", np.exp(a))
print("Square root:", np.sqrt(a))
print("Logarithm:", np.log(a))

matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])

print("Dot Product:", np.dot(matrix_A, matrix_B))
print("Inverse of A:", np.linalg.inv(matrix_A))
print("Determinant of A:", np.linalg.det(matrix_A))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Square root: [1.         1.41421356 1.73205081]
Logarithm: [0.         0.69314718 1.09861229]
Dot Product: [[19 22]
 [43 50]]
Inverse of A: [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004


Task 3: Slicing and Indexing

In [9]:
arr = np.array([10, 20, 30, 40, 50])
print("First three elements:", arr[:3])
print("Last two elements:", arr[-2:])
print("Every other element:", arr[::2])

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("First two rows:", arr_2d[:2, :])
print("Last column:", arr_2d[:, -1])

First three elements: [10 20 30]
Last two elements: [40 50]
Every other element: [10 30 50]
First two rows: [[1 2 3]
 [4 5 6]]
Last column: [3 6 9]


Task 4: Broadcasting

In [10]:
A = np.array([[1], [2], [3]])
B = np.array([10, 20, 30])

C = A + B
print("Broadcasting result:", C)

Broadcasting result: [[11 21 31]
 [12 22 32]
 [13 23 33]]


Task 5: Error Handling in NumPy

In [11]:
arr = np.array([1, 2, 3])
try:
  print(arr[5])
except IndexError as e:
  print("IndexError:", e)

try:
  a = np.array([1, 2, 3])
  b = np.array([[4, 5], [6, 7]])
  print(a + b)
except ValueError as e:
  print("ValueError:", e)

IndexError: index 5 is out of bounds for axis 0 with size 3
ValueError: operands could not be broadcast together with shapes (3,) (2,2) 


In [ ]:
import numpy as np
import time


size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
list_add = [x + y for x, y in zip(list1, list2)]
print("Python List Addition:", time.time() - start, "seconds")

start = time.time()
arr_add = arr1 + arr2
print("NumPy Array Addition:", time.time() - start, "seconds")

start = time.time()
list_mul = [x * y for x, y in zip(list1, list2)]
print("Python List Multiplication:", time.time() - start, "seconds")

start = time.time()
arr_mul = arr1 * arr2
print("NumPy Array Multiplication:", time.time() - start, "seconds")

start = time.time()
dot_product = sum(x * y for x, y in zip(list1, list2))
print("Python List Dot Product:", time.time() - start, "seconds")

start = time.time()
dot_product_np = np.dot(arr1, arr2)
print("NumPy Array Dot Product:", time.time() - start, "seconds")

size = 1000
matrix1 = [[i for i in range(size)] for _ in range(size)]
matrix2 = [[i for i in range(size)] for _ in range(size)]
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start = time.time()
matrix_result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
print("Python List Matrix Multiplication:", time.time() - start, "seconds")

start = time.time()
matrix_result_np = np.dot(matrix1_np, matrix2_np)
print("NumPy Array Matrix Multiplication:", time.time() - start, "seconds")
